### ISSUE TITLE
RFC on a changing GuestManager.convert to update in-place

### ISSUE THREAD

**Issue by mbhynes** [julianwachholz/django-guest-user#4]
Hi @julianwachholz,

First off, thank you very much for maintaining this package for new versions of Django!

I've opened this ticket to propose a relatively simple change (or addition) of the `GuestManager` in the package that I think would enable greater functionality for devs wanting to create *guest users*.

### Business Use Case

I started using this package to enable guest users functionality on a site, with the goal that:
- ephemeral guest users would be able to modify the db (ie CRUD their own objects like a regular user)
- after conversion all of the state in related models would be *maintained*

After reading the documentation for `django-guest-user` I didn't see any flags that stated this usage *wasn't* possible, but after installing the package and trying to use it, to the best of my understanding, the use case above is not supported. I think this has also been raised previously in https://github.com/julianwachholz/django-guest-user/issues/3. 

## EDIT:

- This use case is supported; I had a misconfigured form and had misread the guest creation workflow when debugging.

Thanks very much for your time!

**Comment by julianwachholz** [comment]
Heya! Thanks for the kind words!
I'm going to have to take a deeper look into your other concerns one by one at a later date but I want to address your first point, the business use case.

What you're describing is exactly how guest users are intended to be used and working. It's possible you may have found a bug where converting will create a new user instead of only deleting the Guest instance?

[The last line in this test verifies that converting a Guest keeps the User PK](https://github.com/julianwachholz/django-guest-user/blob/9faee491cb6f7c5d7285aa165c91d3b2a81e2533/test_proj/test_managers.py#L74)

**Comment by mbhynes** [comment]
Thanks very for your reply! I must have something miscondigured on my end, and I'll take a closer look.

**Comment by mbhynes** [comment]
Ah, I see my problems:
- I had a misconfigured `GUEST_USER_CONVERT_FORM` that subclassed `UserCreationForm`, but was pointing to the wrong post endpoint; so I was creating new users rather than upserting an existing one 🤦 
- I also misread the `guest_user.models` code and mistakenly thought that the guest `User` record was being deleted in `GuestManager.convert()`, when it's just the `Guest` record being deleted, and had missed that the `User` instance was supposed to be bound in the form view (because I had the wrong endpoint, my guest User instances were not being bound)

Thanks very much for your time and helping me debug from afar ...
